name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set output
        run: echo ::set-output name=tag::"234455"
      - name: Test
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Test2
        run: |
          mv  ./dist/app_32.md ./dist/app_change_32.md
          mv  ./dist/app_64.md ./dist/app_change_64.md
          ls dist
      - name: Test3
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          mv  ./dist/app_change_32.md ./dist/app_${{env.RELEASE_VERSION}}_32.md
          mv  ./dist/app_change_64.md ./dist/app_${{env.RELEASE_VERSION}}_64.md
          ls dist
      # - uses: actions/checkout@v2
      # - name: Install Node.js, NPM and Yarn
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      # - name: Install node modules
      #   run: npm install
      # - name: Build 32 & 64 bit version
      #   run: |
      #     npm run pack:win32
      #     ren  dist\MiigoDataLogger-1.5.0.exe MiigoDataLogger-1.5.0_32.exe
      #     npm run pack:win64
      #     ren  dist\MiigoDataLogger-1.5.0.exe MiigoDataLogger-1.5.0_64.exe
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: upload to google drive
      #   run: node upload.js
      #   env:
      #     TOKEN: ${{ secrets.TOKEN }}
      #     CREDENTIALS: ${{ secrets.CREDENTIALS }}
